using System;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Janela "Vincular ao site": gera um codigo curto no cliente, pede ao servidor para
/// registra-lo (comando vincularsite), e mostra o codigo para o jogador colar no site.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class VincularSiteWindow : DefaultWindow
{
    // Sem 0/O/1/I para nao confundir quem digita.
    private const string Alfabeto = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

    public VincularSiteWindow()
    {
        RobustXamlLoader.Load(this);

        var rng = new Random();
        var chars = new char[4];
        for (var i = 0; i < 4; i++)
            chars[i] = Alfabeto[rng.Next(Alfabeto.Length)];
        var code = "HONK-" + new string(chars);

        CodeEdit.Text = code;

        // Registra o codigo no servidor. vincularsite e [AnyCommand]; roda no servidor.
        IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand($"vincularsite {code}");

        StepsLabel.SetMessage(
            "1. Copie o codigo abaixo.\n" +
            "2. Entre em honkenvironment.online/portal com o Discord.\n" +
            "3. Cole o codigo e confirme.");
        StatusLabel.Text = "";

        CopyButton.OnPressed += _ =>
        {
            IoCManager.Resolve<IClipboardManager>().SetText(code);
            StatusLabel.Text = "Codigo copiado.";
        };
        FecharButton.OnPressed += _ => Close();
    }
}
